import { describe, it, expect } from 'vitest';
import { WalkInSessionRequest } from '../src/queues.js';

/**
 * What the Yiji app is allowed to send to `POST /walk-in/session`.
 *
 * THE BUG THIS EXISTS FOR (2026-09-09). The app was told to mint its own JWT —
 * "the token will be generated by your backend" — but was never given a signing
 * secret, so every token it produced failed verification. Twelve
 * `token invalid: invalid signature` rejections in the production log, and a
 * customer staring at "Connecting…" for ever.
 *
 * The app never needed to sign anything: this endpoint takes a phone number and
 * returns a token minted with the gateway's own secret. What it DID need was
 * somewhere to put the two things it knows and the gateway cannot derive — the
 * customer's real Yiji id, and their name.
 *
 * `customerId` is the one that matters beyond cosmetics: it becomes
 * `external_customer_id`, which the coupon push sends to Yiji as `userId`. A
 * phone-derived handle there is a coupon that cannot be delivered.
 */
describe('WalkInSessionRequest', () => {
  it('accepts the shape a QR walk-in sends: a phone and nothing else', () => {
    // Nobody at a counter knows the customer's Yiji id, so it must stay optional.
    const r = WalkInSessionRequest.safeParse({ phone: '0512345678' });
    expect(r.success).toBe(true);
  });

  it('accepts the shape the Yiji app sends, ids and all', () => {
    const r = WalkInSessionRequest.safeParse({
      phone: '+966512345678',
      customerId: '12345',
      name: 'Fatima',
    });
    expect(r.success).toBe(true);
    if (r.success) {
      expect(r.data.customerId).toBe('12345');
      expect(r.data.name).toBe('Fatima');
    }
  });

  it('takes E.164, which is how the app writes a number', () => {
    // The app sends +9665…, a counter types 05… . Both are the same customer,
    // and the gateway normalises them to one stored form.
    expect(WalkInSessionRequest.safeParse({ phone: '+966512345678' }).success).toBe(true);
    expect(WalkInSessionRequest.safeParse({ phone: '0512345678' }).success).toBe(true);
    expect(WalkInSessionRequest.safeParse({ phone: '05 1234 5678' }).success).toBe(true);
  });

  it('rejects a phone that could not be one', () => {
    expect(WalkInSessionRequest.safeParse({ phone: '' }).success).toBe(false);
    expect(WalkInSessionRequest.safeParse({ phone: '051' }).success).toBe(false);
    expect(WalkInSessionRequest.safeParse({ phone: 'not-a-number' }).success).toBe(false);
    expect(WalkInSessionRequest.safeParse({}).success).toBe(false);
  });

  it('rejects an empty customerId rather than storing a blank Yiji id', () => {
    // Absent means "unknown", which the gateway handles. Empty-string would be
    // a value that means nothing and would reach Yiji as a userId.
    expect(WalkInSessionRequest.safeParse({ phone: '0512345678', customerId: '' }).success).toBe(
      false,
    );
    expect(WalkInSessionRequest.safeParse({ phone: '0512345678', customerId: '  ' }).success).toBe(
      false,
    );
  });

  it('leaves vendorId optional, so the app need not guess ours', () => {
    // It is our internal id; asking a third party for it only invited a wrong
    // one. The gateway falls back to DEFAULT_VENDOR_ID.
    const r = WalkInSessionRequest.safeParse({ phone: '0512345678' });
    expect(r.success).toBe(true);
    if (r.success) expect(r.data.vendorId).toBeUndefined();
  });

  it('accepts email, which the app has and a counter does not', () => {
    const r = WalkInSessionRequest.safeParse({
      phone: '+966512345678',
      customerId: '12345',
      name: 'Fatima',
      email: 'fatima@example.com',
    });
    expect(r.success).toBe(true);
    if (r.success) expect(r.data.email).toBe('fatima@example.com');
  });

  it('rejects an email that is not one, rather than storing it', () => {
    // A malformed address on a contact is worse than none: it looks like a way
    // to reach the customer and is not.
    expect(
      WalkInSessionRequest.safeParse({ phone: '0512345678', email: 'not-an-email' }).success,
    ).toBe(false);
  });

  it('needs ONLY the phone — every other field may be omitted', () => {
    /* The contract given to the Yiji app (owner, 2026-09-09): phone mandatory,
       customerId/name/email optional-but-send-them, and vendorId not asked for
       at all because it is a CRM concept. */
    const r = WalkInSessionRequest.safeParse({ phone: '+966512345678' });
    expect(r.success).toBe(true);
    if (r.success) {
      expect(r.data.customerId).toBeUndefined();
      expect(r.data.name).toBeUndefined();
      expect(r.data.email).toBeUndefined();
      expect(r.data.vendorId).toBeUndefined();
    }
  });
});
